package netgloo.models;
// Generated Aug 25, 2017 1:26:26 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SubUsersId generated by hbm2java
 */
@Embeddable
public class SubUsersId implements java.io.Serializable {

	private long id;
	private long subId;

	public SubUsersId() {
	}

	public SubUsersId(long id, long subId) {
		this.id = id;
		this.subId = subId;
	}

	@Column(name = "id", nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "sub_id", nullable = false)
	public long getSubId() {
		return this.subId;
	}

	public void setSubId(long subId) {
		this.subId = subId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SubUsersId))
			return false;
		SubUsersId castOther = (SubUsersId) other;

		return (this.getId() == castOther.getId()) && (this.getSubId() == castOther.getSubId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result + (int) this.getSubId();
		return result;
	}

}
